name: Alps
favicon: null
layout_spectrum: 0.24255
typography_spectrum: 0.66468
title: Alps
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#242930'
    - '#cdcdcd'
    - '#ffffff'
    - '#999999'
    - '#808080'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: 2c164be5-fdf1-4041-b88b-1087429ff7c6
    url: null
